### ISSUE TITLE
Piston automation failure

### ISSUE THREAD

**Issue by Lyther** [phil14052/CustomCobbleGen#21]
**Describe the bug**
While enabled 'automation-pistons' in config, the piston still cannot work in skyblock.

**To Reproduce**
1. Place water and lava, generate success in the middle.
2. Use piston to push block away with piston cobble stone producer.
3. The block always becomes cobble.
_Maybe need multiple players using this generator._

**Expected behavior**
The generator works well instead of making blocks become cobble stones.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Plugin version: 1.4.0
 - MC version: 1.15.2 Paper

**Comment by phil14052** [comment]
Hi @Lyther,
I can't seem to reproduce this bug. Can you send your config.yml file and a screenshot of your generator?

- Phil

**Comment by Lyther** [comment]
Dear phil,
I've fixed it already. This bug is caused by in-proper disable of plugin
(or maybe normal exit) and pistons information doesn't save.
So I extract the method to detect nearest player and judge piston according
to nearest player uuid instead of config player uuid.
Thanks for response. I'll close the issue.

phil14052 <notifications@github.com> 于 2020年3月16日周一 20:27写道：
