### ISSUE TITLE
Only Making Cobble in a certain way (Piston bug) - Maybe not a plugin problem

### ISSUE THREAD

**Issue by Falasteen1** [phil14052/CustomCobbleGen#23]
**Describe the bug**
When making a generator a certain way, it only produces cobblestone.

**To Reproduce**
It seems like this happens in any generator that forces multiple blocks of lava to touch multiple blocks of water at the same exact time.

**Expected behavior**
Expected multiple ores.

**Console errors**
I had to turn Debug mode on for this to show up
"[Server] INFO [CustomCobbleGen]: Debug - GB has expired"
This comes up for every block that produces cobblestone instead of ores.

**Config file**
https://hastebin.com/pojeyefogi.php

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: [Not Sure, On hosting service]
 - Plugin version: [1.15.2]
 - MC version: [1.15.2]

**Additional context**

**Comment by vadoreledingue** [comment]
Same dont work with this farm : https://www.youtube.com/watch?v=n_6azSaOU2g 
( piston have been reloaded ... )

**Comment by phil14052** [comment]
Hi, I will look into this.
@Falasteen1 can you send me a screenshot of your cobblestone generator?
@vadoreledingue I will try yours now

**Comment by phil14052** [comment]
@vadoreledingue I can't seem to recreate the problem with the one you linked to. A fix for you could be if you broke all the cobblestone above then pistons once. This will update the infomation on the pistons. Also remember to enable pistons in the config. If this does not work, then I would like to know which version of the plugin you are using. I have tested it on the 1.4.0 version and the design from the youtube video seems to work there.

@Falasteen1 It seems like hastebin has deleted your config, so I can't find it. Also what plugin version are you running? You wrote 1.15.2 in the description, but I meant the plugin version. The one you downloaded from spigot.

**Comment by vadoreledingue** [comment]
after having broken and replaced the pistons it works, but when I restart the server it doesn't work anymore. @phil14052  ( plugin version 1.4.0 )

**Comment by vadoreledingue** [comment]
? @phil14052

**Comment by phil14052** [comment]
Hi @vadoreledingue, Sorry I did not get a message from Github about your reply 5 days ago.
Can you send me the console log of when you restart the server? And also the players.yml before and after restart?

**Comment by vadoreledingue** [comment]
[playersbefore.txt](https://github.com/phil14052/CustomCobbleGen/files/4469292/playersbefore.txt)
[playersafter.txt](https://github.com/phil14052/CustomCobbleGen/files/4469293/playersafter.txt)
[latest.log](https://github.com/phil14052/CustomCobbleGen/files/4469294/latest.log)

**Comment by vadoreledingue** [comment]
( first time i have an error with the plugin at the restart ) @phil14052

**Comment by phil14052** [comment]
A days ago another person had the same bug but closed the issue because he said it was a problem with his user cache. (https://github.com/phil14052/CustomCobbleGen/issues/22#issuecomment-609609752) Can you send me your user cache?

**Comment by vadoreledingue** [comment]
[usercache.txt](https://github.com/phil14052/CustomCobbleGen/files/4469347/usercache.txt)

@phil14052  ( thanks for your help )

**Comment by vadoreledingue** [comment]
i dont have good understand how to fix the bug ... ( sorry im french )

**Comment by vadoreledingue** [comment]
@phil14052 ?

**Comment by phil14052** [comment]
@vadoreledingue I am looking into the problem. Sadly the problem does not make sense right now. But I will try to fix it in the next update.

**Comment by nateinator** [comment]
Same issue here. Replacing the pistons and knocking the blocks a couple times that sit just in front of the piston fixed the problem, if not only temporarily

**Comment by vadoreledingue** [comment]
when did you relase the next update @phil14052  ?
