### ISSUE TITLE
Somes CobbleStone Generator don't work with Pistons

### ISSUE THREAD

**Issue by Ninatasia** [phil14052/CustomCobbleGen#26]
Hi !
I've a little problem because If I try to use somes automatics generators with pistons, no custom blocs are generated because I've just cobblestone, to work I need to break all blocs with hand or tools I've try to add an bigger delay before blocks are pushed by pistons and he don't work.

Pistons : Don't work
Hand : Work

Into my configuration :
```
debug: false
options:
  generationModes:
    '0':
      firstBlock: water
      secondBlock: lava
  playerSearchRadius: 4.0
  money:
    format: true
  gui:
    showBarrierBlockIfLocked: false
    hideInfoIfLocked: false
    confirmpurchases: true
    admingui: true
  signs:
    enabled: true
  automation:
    pistons: true
  disabled:
    worlds:
    - world_nether
    - world_the_end
```

It's a SkyBlock, my world is named skyblock, If I try into an other world, it don't work with pistons.

Have a second little problem with cost of tier If I define the price with money and items I need just to pay with money and not with money and items exemple of my config :
```
      price:
        money: 40000
        item:
          BLAZE_ROD: 64
      contains:
```

Without thats two problems is just AMAZING ! Thank u for this plugins and carry on. 👌

Sorry for my very poor english, just I doesn't like use google translator, because I would like learn more to upgrade my english level. 😂

King regard.
Ninatasia.

**Comment by Ninatasia** [comment]
Nobody can help me ? :|

**Comment by phil14052** [comment]
Hi sorry for no reply. I haven't had that much time. The piston bug may be fixed in the next version.

The other thing is not really a bug. It was not intended to only have items as a requirement. But it may be added in the future.

- Phil

**Comment by Ninatasia** [comment]
It would be great if it was solved and if it was also possible to buy with items / blocks and XP, it would make the plugin even more complete and it would do me a lot of service because I don't know how to do otherwise now: |

As a small idea, it might be nice to be able to organize the menu as desired, a bit like DeluxeMenu.

Otherwise great job for this magnificent plugins :)
Keep going like that.

**Comment by Ninatasia** [comment]
> The piston bug is noted see Issue #23 and the fix is currently being tested.
I'm in a hurry for the update to arrive.

> I don't know if I have misunderstood your question but you can set items/blocks and XP as a price. So you can

If I config the price of the tier 4 into 10000$ and diamond block, the player need just to pay 10000$ and no diamond is removed and if the player haven't diamond block he can buy without.
And the required items don't apear into the menu.

> There are going to be more config options to the GUI in the next version. But sadly not as customizable as DeluxeMenu

Very nice. :D
