### ISSUE TITLE
Force save on each tier purchase

### ISSUE THREAD

**Issue by plagoutte** [phil14052/CustomCobbleGen#28]
**Is your feature request related to a problem? Please describe.**
If the server crashes, all players who buyed a tier between the crash and the latest save lose it.

**Describe the solution you'd like**
A setting to force save (to the datafile) on each tier purchase.

**Describe alternatives you've considered**
None

**Additional context**
None

I remain available for any further information.

**Comment by phil14052** [comment]
Hi! Sounds like a great feature!

I will add it when I get time. But for now there is the /ccg admin forcesave command. Which will save all data for you. You can maybe find a plugin that automatically runs this command x times a day. But I will be adding this in the plugin at some point.

**Comment by plagoutte** [comment]
Hi, thanks for your quick reply !

I scheduled `ccg admin forcesave` command each 10 minutes to limit tier lose risk.

It would be great to see this feature in the future ! :)

**Comment by phil14052** [comment]
Added in #32
