### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by Ninatasia** [phil14052/CustomCobbleGen#31]
Is it possible to have a placeholder like %buyed_tier_nameoftier% that would return "true" or "false" depending on whether the tier was purchased or not ?

**Comment by phil14052** [comment]
I will add this to the todo list

**Comment by Ninatasia** [comment]
Okay thx, u know can make that in few days ?

**Comment by phil14052** [comment]
Hey! I have added this to the PlaceholderAPI placeholders which means it can be used almost everywhere but some places. Can I ask you where you need this placeholder?

**Comment by Ninatasia** [comment]
> Hey! I have added this to the PlaceholderAPI placeholders which means it can be used almost everywhere but some places. Can I ask you where you need this placeholder?

Because I would like create a new menu with DeluxeMenu ;)
