### ISSUE TITLE
FabledSkyBlock island level

### ISSUE THREAD

**Issue by ScriptJunkieMC** [phil14052/CustomCobbleGen#36]
**Describe the bug**
When we run the cobble gen using fabled skyblock the island level goes down since it thinks we are mining the Diamond, Emerald, Gold blocks from the stack from the island and not the cobble gen. So it removes levels as we grind the generator. Not sure if this is something fabled has to patch or if you can detect with fabled api.

**To Reproduce**
Setup fabled and ccg (default)
stack some emerald, diamond and iron blocks on your island as usual.
grind the gen and watch the scoreboard level go down when you hit the those blocks in the gen. (Diamond, Emerald, Gold or Iron block)

**Expected behavior**
should check if its fabled stack or not and not mess with the levels when using the generator.

**Console errors**
Is there any errors in the console?
no errors shown

**Config file**
Can you send your config file? Maybe use https://hastebin.com/ to send.
happens on default setup. Havent customized it at this time.

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Plugin version: tried 1.4.1 and 1.4.5
 - MC version: 1.16.2

**Additional context**

**Comment by phil14052** [comment]
Hmm.. seems more like a problem with fabled but I will try to see if the fabled api lets me fix this bug :)

**Comment by phil14052** [comment]
I have added so the plugin will say to FabledSkyblock that they need to we calc the level each time a block is mined from a generator. I do not know if it will fix the problem but FabledSkyblock API does not support setting levels manually.
This will be part of the 1.5.0 update. A beta version will soon be up on the discord.
