### ISSUE TITLE
Fortune not working

### ISSUE THREAD

**Issue by ScriptJunkieMC** [phil14052/CustomCobbleGen#37]
**Describe the bug**
Hitting diamond ore and emerald ore only gives 1 diamond when i have fortune on my netherite pickaxe.

**To Reproduce**
Load gen -> mine ore with hopper below it to collect
obtains 1 at a time when fortune is involved.

**Expected behavior**
- should give random qty with fortune calculation

**Console errors**
Is there any errors in the console?
none

**Config file**
Can you send your config file? Maybe use https://hastebin.com/ to send.
default config

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Plugin version: latest
 - MC version: 1.16.2

**Additional context**

**Comment by ScriptJunkieMC** [comment]
nvm this may be my issue and not plugin related.

**Comment by phil14052** [comment]
Yeah the plugin does not affect block drops. So it is probably not this plugin that has a problem. Hope you're problem got fixed :D
