### ISSUE TITLE
Smaller generators not working

### ISSUE THREAD

**Issue by ScriptJunkieMC** [phil14052/CustomCobbleGen#38]
**Describe the bug**
using a 3 wide generator doesnt activate CCG generation.

**To Reproduce**
Build a 3 wide cobble gen using stair waterlogged.

LAVA - BLANK - STAIR Facing Lava with water placed in it.

**Expected behavior**
SHould generate generator specific ores and items. Only generates cobble.

**Console errors**
Is there any errors in the console?
no errors

**Config file**
Can you send your config file? Maybe use https://hastebin.com/ to send.

**Screenshots**
let me know if ya need this

**System (please complete the following information):**
 - OS: Windows
 - Plugin version: Latest
 - MC version: 1.16.2

**Additional context**

**Comment by ScriptJunkieMC** [comment]
i do notice the waterlogged blocks support in config. Would this just be search radius to 3?

**Comment by phil14052** [comment]
The waterlogged option both checks for water and waterlogged blocks. It does not use any radius.
If you still have the problem can you then send me your config. A screenshot would also help

**Comment by ScriptJunkieMC** [comment]
Seems to work after a reboot now. Was odd it was only showing cobble for hours for everyone when they used the 3 wide cobble gen format.

**Comment by phil14052** [comment]
Hmm weird. Seems like the config wasn't correctly reloaded. Happy to hear it works now
