### ISSUE TITLE
Possible for players to be able to enable disable ding noise?

### ISSUE THREAD

**Issue by ScriptJunkieMC** [phil14052/CustomCobbleGen#39]
**Is your feature request related to a problem? Please describe.**
A way for players to enable / disable ding noises. (getting hella lot of complaints LOL)

**Describe the solution you'd like**
Flag under user UI to be able to disable the noise.

**Describe alternatives you've considered**
Telling user to turn off MC sounds. Not much of a solution though.

**Additional context**
None that i can think of.

**Comment by phil14052** [comment]
Hi, yeah sorry about this. There is a version on the discord server that fixes the bug that you can’t disable the sound.
Direct link to the file: https://discord.com/channels/633700649783132181/744151065540165682/769940134191693864

Vanilla minecraft actually also has a sound it is just a different one. You can also change it in the config to this sound. A list of sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
I think the vanilla one is called BLOCK_FIRE_EXTINGUISH

Hope it helps
